spring:
  datasource:
    # Use localhost and the EXPOSED port (5434)
    url: jdbc:postgresql://localhost:5434/classes
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    # === ADD THIS LINE ===
    defer-datasource-initialization: true # This is the magic fix!
    # =====================
    show-sql: true
  sql:
    init:
      mode: always
server:
  port: 8082