spring:
  datasource:
    # Use localhost and the EXPOSED port (5434) for local development
    url: jdbc:postgresql://localhost:5434/classes
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
    # This property fixes the startup race condition
    defer-datasource-initialization: true
    show-sql: true
  sql:
    init:
      # This ensures data.sql runs every time
      mode: always
server:
  port: 8082