server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://user-db:5432/users   # user-db = Docker Service Name
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none   # Hibernate erstellt keine Tabellen
    show-sql: true

  sql:
    init:
      mode: always     # schema.sql und data.sql werden ausgeführt
